// <auto-generated />
namespace BongTaiXinhShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class chang_key : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(chang_key));
        
        string IMigrationMetadata.Id
        {
            get { return "202305291448203_chang_key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
